package apa.fun;
public class MeNMyKup {
    public static void main(String[] args){
        String[] l={
            "Yeah, don't play with me, I'm on some other shit, like",
            "Some whole other shit, like",
            "(Star made the beat, I just took it out the oven)",
            "Huh, huh, huh, huh, huh, huh",
            "It's just me and my cup in this bitch",
            "DRKSHDW all on my Rick",
            "VVS all on my wrist",
            "I bought an Uzi today, and it's already hot, it ain't come with a cooling kit",
            "She ain't fuck with me back then, but wanna fuck with me now, huh, I'm cool, lil' bitch",
            "Huh, let's go hit a lick",
            "Huh, let's go do a drill",
            "I heard he got a mill' in his crib, and he stay up in the hills (8-808)",
            "We don't give a fuck who you is, we don't give a fuck how you feel",
            "We don't give a fuck how you feel, we don't give no fucks",
            "I copped a Mercedes, I ditched that AMG, I'm ridin' the G-Wagon Truck",
            "I just might go buy the SVJ, 'cause I like how the doors go up",
            "My boy, he be catchin' them bodies, he catchin' them bodies, I'm watching the scores go up",
            "Yo' gang probably caught a few bodies, but I ain't worried about it, 'cause we droppin' more than them",
            "Step on shit like Timbs, pull up with a FN Five-seveN, that bih' take off limbs",
            "I just popped a private jet, G6, I'm 'bout to take off, yeah",
            "They like, 'Hold up, hold up, hold up, you boutta take off right here'",
            "I'm 'boutta take off, yeah",
            "Niggas ain't fuckin' with me when it come to swag, huh, I'm passin' it out",
            "Shawty got no respect when it come to that ass, huh, she passin' it out",
            "I be VET-VET-VETEMENTS from head to toe, even the sock",
            "I got every Balenciaga boots, except for the Crocs",
            "Rick Owens all over my, Rick Owens all over me",
            "Maison Francis cologne, got this hoe all over me",
            "I pulled up to my show, rock out this bitch, then I leave",
            "I don't fuck with these niggas, like they got a disease",
            "Trapper rapper, huh-huh, I got what you need",
            "I got that bitch in H&M, then now she rock double C",
            "I got that bitch named Gabriela and now she rocks double G",
            "I took my other bitch to Louis Vuitton and bought her everything, yeah-yeah",
            "If it's up then it's stuck, leave it in the air",
            "Missionary, her legs up, I got them in the air",
            "This bitch a freak, this bitch let me fuck her anywhere",
            "Shawty whip it out in front of my partner, she don't even care",
            "I'm elite with these hoes",
            "I'll put a bitch in her place, I'll tell that bitch where to go",
            "If I tell that lil' bitch to dance, she gon' tango",
            "If I tell her to paint me a picture, she gon' Van Gogh",
            "She insane with that throat, she insane wit' it",
            "I told her she insane, if she gon' let the gang hit",
            "I pass her to the gang, yeah, just like James, nigga",
            "I be killin' that pussy, be killin' that pussy feel like John Wayne, nigga",
            "He was talkin' that, huh, and all he heard was a bang, nigga",
            "Give a fuck who you fuck with, long as you don't fuck with my gang, nigga",
            "Give a fuck who you fuck with, long as you don't fuck with my gang, nigga",
            "Huh, huh, huh, huh, huh, huh",
            "It's just me and my cup in this bitch",
            "DRKSHDW all on my Rick",
            "VVS all on my wrist",
            "I bought an Uzi today, and it's already hot, it ain't come with a cooling kit",
            "She ain't fuck with me back then, but wanna fuck with me now, huh, I'm cool, lil' bitch",
            "Huh, let's go hit a lick",
            "Huh, let's go do a drill",
            "I heard he got a mill' in his crib, and he stay up in the hills (8-808)",
            "We don't give a fuck who you is, we don't give a fuck how you feel",
            "We don't give a fuck how you feel, we don't give no fucks",
        };
        for(int i=0;i<l.length;i++){System.out.println(l[i]);}
    }
}